spring:
  cloud:
    loadbalancer.ribbon:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://database:5432/Sovcombank
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8076/eureka/
server:
  port: 8060
