spring:
  cloud:
    loadbalancer.ribbon:
      enabled: false
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8076/eureka/
server:
  port: 8061
management:
  endpoints:
    web:
      exposure:
        include: '*'
springdoc:
  swagger-ui:
    configUrl: /swagger-config.json
