spring:
    application:
        name: orderService
    security:
        oauth2:
            resource-server:
                jwt:
                    issuer-uri: ${KEYCLOAK_ISS_URI:http://keycloak:8080/realms/sovcombank-realm}
                    jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
    datasource:
        url: jdbc:postgresql://${DB_HOST:database}:${DB_PORT:5432}/${DB:orderservice}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres}
    cloud:
        loadbalancer:
            enabled: false
        function:
            definition: handleOrder;orderCreatedSupplier;orderChangedSupplier
        stream:
            bindings:
              handleOrder-in-0:
                  destination: order-changed-topic
              orderChangedSupplier-out-0:
                  destination: order-changed-topic
              orderCreatedSupplier-out-0:
                  destination: order-created-topic
            default-binder: kafka
    messages:
        basename: messages
        use-code-as-default-message: true
    jpa:
        hibernate:
            ddl-auto: create
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://${EUREKA_HOST:eurekaserver}:${EUREKA_PORT:8076}/eureka/
server:
    port: 8120
management:
    endpoints:
        web:
            exposure:
                include: '*'
jwt:
    auth:
        converter:
            principal-attribute: preferred_username
            resource-id: order_client
